# CommandMaker Config

config:
  enabled-commands: # Add the names of every command you want to have enabled here
    - examplecommand

# You can use {player} placeholder in messages or commands
# Add as many commands as you want

commands:
  examplecommand: # This will be the name of the command label. This would be /examplecommand to run
    aliases: # Other commands that will also trigger these actions. Remove line if there are no aliases
      - examplescommand
    actions:
      - "MESSAGE:&6&lHello! <green>This is the example!" # Send a message. Both legacy formatting & minimessage supported
      - "CONSOLE:say Hello!" # Send console commands
      - "PLAYER:say Hiii" # Send commands as player
      - "CONSOLE:give {player} {Arg2}"
    permission: "commandmaker.example" # Permission required to run the command. leave blank/remove line to disable
    args: # Arguments for the command. Can be removed if not needed for the command
      'Arg1':
        # Arguments are additional information you can add to the command. Args will be accessible as placeholders in your actions
        # This argument section is named Arg1, so the placeholder will be {Arg1}
        # Argument options:
        # PLAYER - Any online player. Will tab complete
        # STRING - Can be any string
        # INT - Any whole number
        # FLOAT - Any Number w/ decimals
        type: PLAYER
        placeholder: true # Only for player type. If true, this player will be given to PAPI instead of the sender
      'Arg2':
        type: STRING
        options: # Optional, list of strings that will be accepted for this argument
          - "cooked_porkchop"
          - "cooked_beef"



