# CommandMaker Config
# More in-depth config information and setup help
# can be found on my wiki https://kingidk.net

# Most of this can be easily edited through commands in-game.
# if you wish to edit it manually, you still can though! Theres a section
# in the wiki about it

config:
  enabled-commands:
    - examplecommand


commands:
  examplecommand:
    aliases:
      - examplescommand
    actions:
      - "MESSAGE:&6&lHello! <green>This is the example!"
      - "CONSOLE:give {Arg1} stick 1"
      - "PLAYER:say Hiii"
      - "BROADCAST:Hey!"
    permission: "commandmaker.example"
    args:
      'Arg1':
        type: PLAYER




