name: CommandMaker
version: '1.4.0'
main: net.kingidk.commandMaker.CommandMaker
api-version: '1.21'
authors: [ Kingidk ]
folia-supported: true

commands:
  commandmaker:
    usage: /commandmaker reload
    description: Commandmaker Admin Command
    aliases: [cm]

permissions:
  commandmaker.admin:
    description: Admin command
    default: op
